[2024-09-15T02:40:16.904+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:40:16.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:40:16.924+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:40:16.923+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:40:17.276+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:40:17.261+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    import build_dataframe
ModuleNotFoundError: No module named 'build_dataframe'
[2024-09-15T02:40:17.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:40:17.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.716 seconds
[2024-09-15T02:41:42.712+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:41:42.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:41:42.720+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:41:42.716+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:41:42.779+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:41:42.766+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    import build_dataframe
ModuleNotFoundError: No module named 'build_dataframe'
[2024-09-15T02:41:42.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:41:42.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.106 seconds
[2024-09-15T02:42:13.109+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:42:13.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:42:13.120+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:42:13.119+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:42:13.216+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:42:13.189+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    import build_dataframe
ModuleNotFoundError: No module named 'build_dataframe'
[2024-09-15T02:42:13.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:42:13.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.166 seconds
[2024-09-15T02:42:43.786+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:42:43.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:42:43.831+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:42:43.829+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:42:43.915+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:42:43.907+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    import build_dataframe
ModuleNotFoundError: No module named 'build_dataframe'
[2024-09-15T02:42:43.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:42:44.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.403 seconds
[2024-09-15T02:43:14.416+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:43:14.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:43:14.422+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:43:14.422+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:43:14.479+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:43:14.466+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    import build_dataframe
ModuleNotFoundError: No module named 'build_dataframe'
[2024-09-15T02:43:14.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:43:14.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.094 seconds
[2024-09-15T02:43:45.010+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:43:45.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:43:45.023+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:43:45.023+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:43:45.057+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:43:45.049+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    import build_dataframe
ModuleNotFoundError: No module named 'build_dataframe'
[2024-09-15T02:43:45.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:43:45.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.076 seconds
[2024-09-15T02:44:15.320+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:44:15.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:44:15.348+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:44:15.347+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:44:20.451+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:44:20.423+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:44:20.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:44:20.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 5.179 seconds
[2024-09-15T02:44:50.810+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:44:50.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:44:50.819+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:44:50.818+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:44:51.386+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:44:51.365+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:44:51.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:44:51.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.606 seconds
[2024-09-15T02:45:21.698+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:45:21.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:45:21.701+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:45:21.701+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:45:22.116+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:45:22.110+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:45:22.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:45:22.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.441 seconds
[2024-09-15T02:45:52.467+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:45:52.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:45:52.472+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:45:52.472+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:45:53.119+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:45:53.105+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:45:53.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:45:53.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.681 seconds
[2024-09-15T02:46:23.345+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:46:23.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:46:23.351+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:46:23.350+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:46:23.430+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:46:23.419+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:46:23.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:46:23.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.114 seconds
[2024-09-15T02:46:53.936+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:46:53.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:46:54.089+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:46:54.089+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:46:54.136+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:46:54.128+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules.build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:46:54.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:46:54.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.227 seconds
[2024-09-15T02:47:12.130+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:47:12.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:47:12.134+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:47:12.133+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:47:12.198+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:47:12.184+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:47:12.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:47:12.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.110 seconds
[2024-09-15T02:47:42.719+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:47:42.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:47:42.725+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:47:42.724+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:47:42.765+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:47:42.755+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:47:42.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:47:42.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.087 seconds
[2024-09-15T02:48:13.238+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:48:13.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:48:13.244+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:48:13.243+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:48:13.271+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:48:13.264+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:48:13.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:48:13.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.082 seconds
[2024-09-15T02:48:43.521+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:48:43.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:48:43.525+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:48:43.524+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:48:43.566+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:48:43.554+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:48:43.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:48:43.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.080 seconds
[2024-09-15T02:49:13.841+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:49:13.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:49:13.847+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:49:13.846+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:49:13.901+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:49:13.884+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:49:13.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:49:13.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.097 seconds
[2024-09-15T02:49:44.094+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:49:44.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:49:44.103+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:49:44.102+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:49:44.151+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:49:44.141+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:49:44.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:49:44.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.090 seconds
[2024-09-15T02:50:14.422+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:50:14.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:50:14.427+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:50:14.427+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:50:14.476+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:50:14.464+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:50:14.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:50:14.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.086 seconds
[2024-09-15T02:50:44.756+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:50:44.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:50:44.762+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:50:44.762+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:50:44.841+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:50:44.820+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 4, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:50:44.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:50:44.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.114 seconds
[2024-09-15T02:51:10.087+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:51:10.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:51:10.093+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:51:10.092+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:51:10.158+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:51:10.146+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:51:10.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:51:10.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.097 seconds
[2024-09-15T02:51:40.390+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:51:40.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:51:40.395+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:51:40.395+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:51:40.464+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:51:40.445+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:51:40.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:51:40.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.104 seconds
[2024-09-15T02:52:11.019+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:52:11.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:52:11.024+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:52:11.024+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:52:11.070+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:52:11.061+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:52:11.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:52:11.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.085 seconds
[2024-09-15T02:52:41.292+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:52:41.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T02:52:41.298+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:52:41.298+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:52:41.355+0000] {logging_mixin.py:190} INFO - [2024-09-15T02:52:41.340+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T02:52:41.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T02:52:41.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.095 seconds
[2024-09-15T03:01:20.306+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:01:20.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:01:20.320+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:01:20.320+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:01:20.414+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:01:20.394+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:01:20.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:01:20.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.212 seconds
[2024-09-15T03:01:53.741+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:01:53.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:01:53.775+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:01:53.772+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:01:53.828+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:01:53.817+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:01:53.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:01:53.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.244 seconds
[2024-09-15T03:02:24.244+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:02:24.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:02:24.341+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:02:24.341+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:02:24.399+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:02:24.383+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:02:24.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:02:24.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.191 seconds
[2024-09-15T03:02:54.614+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:02:54.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:02:54.620+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:02:54.620+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:02:54.644+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:02:54.638+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:02:54.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:02:54.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.057 seconds
[2024-09-15T03:03:25.135+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:03:25.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:03:25.145+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:03:25.141+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:03:25.197+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:03:25.182+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:03:25.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:03:25.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.103 seconds
[2024-09-15T03:03:55.404+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:03:55.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:03:55.408+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:03:55.408+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:03:55.443+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:03:55.434+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:03:55.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:03:55.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.070 seconds
[2024-09-15T03:04:25.766+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:04:25.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:04:25.774+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:04:25.773+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:04:25.844+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:04:25.825+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:04:25.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:04:25.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.110 seconds
[2024-09-15T03:07:37.791+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:07:37.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:07:37.803+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:07:37.802+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:07:37.856+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:07:37.843+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:07:37.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:07:37.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.103 seconds
[2024-09-15T03:08:08.510+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:08:08.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:08:08.561+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:08:08.557+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:08:08.631+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:08:08.617+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:08:08.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:08:08.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.449 seconds
[2024-09-15T03:08:39.594+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:08:39.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:08:39.600+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:08:39.598+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:08:39.644+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:08:39.633+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:08:39.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:08:39.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.085 seconds
[2024-09-15T03:09:10.254+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:09:10.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:09:10.260+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:09:10.259+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:09:10.312+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:09:10.298+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:09:10.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:09:10.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.095 seconds
[2024-09-15T03:09:40.526+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:09:40.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:09:40.534+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:09:40.534+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:09:40.568+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:09:40.555+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:09:40.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:09:40.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.071 seconds
[2024-09-15T03:10:10.816+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:10:10.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:10:10.820+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:10:10.820+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:10:10.857+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:10:10.848+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:10:10.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:10:10.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.068 seconds
[2024-09-15T03:10:41.065+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:10:41.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:10:41.071+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:10:41.070+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:10:42.701+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:10:42.689+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 2, in <module>
    from envio_mail import send_email
ModuleNotFoundError: No module named 'envio_mail'
[2024-09-15T03:10:42.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:10:42.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 1.661 seconds
[2024-09-15T03:11:13.040+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:11:13.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:11:13.045+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:11:13.044+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:11:13.633+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:11:13.619+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 2, in <module>
    from envio_mail import send_email
ModuleNotFoundError: No module named 'envio_mail'
[2024-09-15T03:11:13.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:11:13.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.632 seconds
[2024-09-15T03:11:44.020+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:11:44.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:11:44.024+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:11:44.023+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:11:44.507+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:11:44.495+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 2, in <module>
    from envio_mail import send_email
ModuleNotFoundError: No module named 'envio_mail'
[2024-09-15T03:11:44.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:11:44.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.521 seconds
[2024-09-15T03:17:32.150+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:17:32.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:17:32.166+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:17:32.166+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:07.866+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:07.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:22:07.888+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:07.887+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:07.957+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:07.944+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:22:07.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:07.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.159 seconds
[2024-09-15T03:22:41.870+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:41.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:22:41.919+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:41.916+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:42.003+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:41.961+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:22:42.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:22:42.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 3.647 seconds
[2024-09-15T03:24:36.799+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:24:36.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:24:36.829+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:24:36.827+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:24:36.915+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:24:36.898+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:24:36.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:24:37.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.251 seconds
[2024-09-15T03:25:07.427+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:25:07.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:25:07.442+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:07.440+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:25:07.491+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:07.476+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:25:07.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:25:07.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.123 seconds
[2024-09-15T03:25:38.654+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:25:38.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:25:38.949+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:38.935+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:25:39.088+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:39.072+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:25:39.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:25:39.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.691 seconds
[2024-09-15T03:26:10.607+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:26:10.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:26:10.624+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:10.616+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:26:10.705+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:10.689+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:26:10.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:26:10.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.209 seconds
[2024-09-15T03:26:41.131+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:26:41.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:26:41.134+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:41.134+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:26:41.960+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:41.770+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:26:41.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:26:42.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.936 seconds
[2024-09-15T03:27:12.823+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:27:12.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:27:12.827+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:12.826+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:27:12.856+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:12.846+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:27:12.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:27:12.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.061 seconds
[2024-09-15T03:27:43.386+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:27:43.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:27:43.392+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:43.392+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:27:43.417+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:43.408+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:27:43.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:27:43.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.063 seconds
[2024-09-15T03:28:13.583+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:28:13.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:28:13.587+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:13.586+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:28:13.620+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:13.610+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:28:13.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:28:13.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.073 seconds
[2024-09-15T03:28:43.997+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:28:43.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:28:44.000+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:44.000+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:28:44.032+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:44.022+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:28:44.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:28:44.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.062 seconds
[2024-09-15T03:29:14.452+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:29:14.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:29:14.456+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:14.456+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:29:14.483+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:14.475+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:29:14.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:29:14.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.135 seconds
[2024-09-15T03:29:45.525+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:29:45.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:29:45.533+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:45.531+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:29:45.563+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:45.554+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:29:45.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:29:45.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.082 seconds
[2024-09-15T03:30:16.067+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:30:16.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:30:16.072+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:16.071+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:30:16.105+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:16.098+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:30:16.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:30:16.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.069 seconds
[2024-09-15T03:30:46.491+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:30:46.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:30:46.495+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:46.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:30:46.528+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:46.519+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:30:46.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:30:46.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.070 seconds
[2024-09-15T03:31:16.903+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:31:16.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:31:16.906+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:16.906+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:31:16.932+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:16.924+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:31:16.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:31:16.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.059 seconds
[2024-09-15T03:31:47.377+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:31:47.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:31:47.380+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:47.380+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:31:47.403+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:47.397+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:31:47.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:31:47.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.052 seconds
[2024-09-15T03:32:17.795+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:32:17.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:32:17.799+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:17.798+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:32:17.834+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:17.824+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:32:17.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:32:17.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.066 seconds
[2024-09-15T03:32:48.218+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:32:48.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:32:48.223+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:48.222+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:32:48.251+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:48.242+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:32:48.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:32:48.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.070 seconds
[2024-09-15T03:33:18.705+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:33:18.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:33:18.712+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:18.711+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:33:18.756+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:18.740+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:33:18.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:33:18.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.094 seconds
[2024-09-15T03:33:49.077+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:33:49.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:33:49.081+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:49.080+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:33:49.109+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:49.101+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:33:49.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:33:49.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.062 seconds
[2024-09-15T03:34:19.483+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:34:19.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:34:19.486+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:19.486+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:34:19.507+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:19.501+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:34:19.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:34:19.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.051 seconds
[2024-09-15T03:34:49.945+0000] {processor.py:186} INFO - Started process (PID=221) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:34:49.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:34:49.949+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:49.948+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:34:49.982+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:49.972+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:34:49.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:34:50.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.067 seconds
[2024-09-15T03:48:01.387+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:48:01.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:48:01.398+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:01.396+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:48:14.949+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:14.048+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:48:14.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:48:17.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 16.057 seconds
[2024-09-15T03:48:47.973+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:48:47.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T03:48:47.991+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:47.987+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:48:49.234+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:49.223+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:48:49.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T03:48:49.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 1.329 seconds
[2024-09-15T23:27:39.951+0000] {processor.py:186} INFO - Started process (PID=55) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:27:39.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:27:39.995+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:39.994+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:27:40.111+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:40.097+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:27:40.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:27:40.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.318 seconds
[2024-09-15T23:28:11.040+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:28:11.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:28:11.061+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:11.060+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:28:11.118+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:11.103+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:28:11.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:28:11.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.171 seconds
[2024-09-15T23:28:41.317+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:28:41.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:28:41.322+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:41.322+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:28:41.357+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:41.348+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:28:41.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:28:41.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.074 seconds
[2024-09-15T23:29:12.045+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:29:12.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:29:12.049+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:12.049+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:29:12.085+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:12.078+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:29:12.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:29:12.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.075 seconds
[2024-09-15T23:29:42.492+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:29:42.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:29:42.495+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:42.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:29:42.539+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:42.534+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ImportError: cannot import name 'llamado_api' from 'modules' (unknown location)
[2024-09-15T23:29:42.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:29:42.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.081 seconds
[2024-09-15T23:30:12.788+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:30:12.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:30:12.791+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:30:12.791+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:30:12.823+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:30:12.817+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:30:12.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:30:12.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.065 seconds
[2024-09-15T23:32:10.452+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:32:10.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:32:10.461+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:10.461+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:32:10.514+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:10.510+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:32:10.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:32:10.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.164 seconds
[2024-09-15T23:32:41.401+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:32:41.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:32:41.451+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:41.445+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:32:41.514+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:41.500+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:32:41.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:32:41.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.327 seconds
[2024-09-15T23:33:12.000+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:33:12.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:33:12.006+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:12.006+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:33:12.035+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:12.030+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:33:12.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:33:12.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.067 seconds
[2024-09-15T23:33:43.101+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:33:43.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:33:43.105+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:43.104+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:33:43.145+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:43.134+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:33:43.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:33:43.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.073 seconds
[2024-09-15T23:34:13.579+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:34:13.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:34:13.587+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:13.586+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:34:13.618+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:13.612+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:34:13.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:34:13.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.159 seconds
[2024-09-15T23:34:44.303+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:34:44.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:34:44.313+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:44.307+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:34:44.338+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:44.332+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 6, in <module>
    from modules import llamado_api,send_email,creacion_df,conexion_RS
ModuleNotFoundError: No module named 'modules'
[2024-09-15T23:34:44.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:34:44.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.059 seconds
[2024-09-15T23:35:08.723+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:35:08.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:35:08.727+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:35:08.726+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:35:09.303+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:35:09.293+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 29, in <module>
    api_call= PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-15T23:35:09.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:35:09.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.602 seconds
[2024-09-15T23:38:07.178+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:38:07.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:38:08.428+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:08.427+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:38:12.692+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:12.684+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 29, in <module>
    api_call= PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-15T23:38:12.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:38:12.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 6.089 seconds
[2024-09-15T23:38:44.486+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:38:44.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:38:44.546+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:44.542+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:38:50.147+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:50.135+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 29, in <module>
    api_call= PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-15T23:38:50.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:38:50.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 5.803 seconds
[2024-09-15T23:39:20.818+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:39:20.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:39:20.824+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:20.823+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:39:22.621+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:22.607+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 29, in <module>
    api_call= PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-15T23:39:22.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:39:22.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 1.874 seconds
[2024-09-15T23:39:53.115+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:39:53.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:39:53.123+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:53.120+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:39:53.787+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:53.777+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 29, in <module>
    api_call= PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-15T23:39:53.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:39:53.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.710 seconds
[2024-09-15T23:40:24.194+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:40:24.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:40:24.197+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:24.197+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:40:24.664+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:24.654+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_etl_cocktails.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl_cocktails.py", line 29, in <module>
    api_call= PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-15T23:40:24.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:40:24.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.496 seconds
[2024-09-15T23:40:53.133+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:40:53.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:40:53.137+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.137+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:40:53.669+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:40:53.919+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.918+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:etl-cocktails
[2024-09-15T23:40:53.929+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.928+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:etl-cocktails
[2024-09-15T23:40:53.938+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.937+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:etl-cocktails
[2024-09-15T23:40:53.950+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.950+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:etl-cocktails
[2024-09-15T23:40:53.952+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.951+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:40:53.975+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:53.975+0000] {dag.py:4156} INFO - Setting next_dagrun for etl-cocktails to 2024-08-25 00:00:00+00:00, run_after=2024-08-26 00:00:00+00:00
[2024-09-15T23:40:54.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.885 seconds
[2024-09-15T23:41:27.571+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:41:27.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:41:27.764+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:41:27.724+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:41:47.175+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:41:47.312+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:41:47.310+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:41:47.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 20.509 seconds
[2024-09-15T23:42:35.322+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:42:35.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:42:35.836+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:42:35.814+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:43:51.654+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:43:51.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:43:51.879+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:43:51.777+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:45:11.225+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:45:11.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:45:11.295+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:45:11.266+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:45:24.902+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:45:26.630+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:45:26.630+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:45:26.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 15.699 seconds
[2024-09-15T23:46:05.895+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:46:05.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:46:06.084+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:46:05.979+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:46:42.408+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:46:42.405+0000] {timeout.py:68} ERROR - Process timed out, PID: 197
[2024-09-15T23:46:42.440+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f1bc94ee980>
[2024-09-15T23:46:42.441+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2024-09-15T23:46:42.444+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2024-09-15T23:46:42.464+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2024-09-15T23:46:42.471+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2024-09-15T23:46:42.472+0000] {logging_mixin.py:190} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2024-09-15T23:46:42.476+0000] {logging_mixin.py:190} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_etl_cocktails.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.1/best-practices.html#reducing-dag-complexity, PID: 197
[2024-09-15T23:46:46.096+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:46:46.388+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:46:46.385+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:46:46.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 41.391 seconds
[2024-09-15T23:47:16.888+0000] {processor.py:186} INFO - Started process (PID=225) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:47:16.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:47:16.941+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:47:16.938+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:47:37.792+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:47:38.061+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:47:38.060+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:47:38.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 21.482 seconds
[2024-09-15T23:48:12.727+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:48:12.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:48:12.940+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:48:12.815+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:48:28.690+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:48:29.522+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:48:29.506+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:48:29.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 20.391 seconds
[2024-09-15T23:49:00.987+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:49:00.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:49:01.026+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:01.008+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:49:09.156+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:49:09.260+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.259+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'etl-cocktails', 'Task Id': 'obtencion-operator', 'Run Id': 'scheduled__2024-09-01T00:00:00+00:00', 'Hostname': 'ef974a20a248', 'External Executor Id': 'dee80197-568b-4f7d-b432-e730e32e2e9c'}
[2024-09-15T23:49:09.316+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.315+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl-cocktails, task_id=obtencion-operator, run_id=scheduled__2024-09-01T00:00:00+00:00, execution_date=20240901T000000, start_date=20240915T234806, end_date=20240915T234909
[2024-09-15T23:49:09.342+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.341+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: etl-cocktails.obtencion-operator scheduled__2024-09-01T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-09-15T23:49:09.349+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.349+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'etl-cocktails', 'Task Id': 'obtencion-operator', 'Run Id': 'scheduled__2024-08-27T00:00:00+00:00', 'Hostname': 'ef974a20a248', 'External Executor Id': '04209945-33ac-4f51-a7fe-73109ae3fd4b'}
[2024-09-15T23:49:09.370+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.370+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl-cocktails, task_id=obtencion-operator, run_id=scheduled__2024-08-27T00:00:00+00:00, execution_date=20240827T000000, start_date=20240915T234205, end_date=20240915T234909
[2024-09-15T23:49:09.390+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.390+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: etl-cocktails.obtencion-operator scheduled__2024-08-27T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-09-15T23:49:09.398+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.397+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'etl-cocktails', 'Task Id': 'obtencion-operator', 'Run Id': 'scheduled__2024-08-30T00:00:00+00:00', 'Hostname': 'ef974a20a248', 'External Executor Id': '44628e18-9d66-425b-8713-8a62074fb3a7'}
[2024-09-15T23:49:09.444+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.444+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl-cocktails, task_id=obtencion-operator, run_id=scheduled__2024-08-30T00:00:00+00:00, execution_date=20240830T000000, start_date=20240915T234802, end_date=20240915T234909
[2024-09-15T23:49:09.454+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.454+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: etl-cocktails.obtencion-operator scheduled__2024-08-30T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-09-15T23:49:09.458+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.458+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'etl-cocktails', 'Task Id': 'obtencion-operator', 'Run Id': 'scheduled__2024-08-29T00:00:00+00:00', 'Hostname': 'ef974a20a248', 'External Executor Id': '69202815-37bd-4fb1-a760-3a339853130c'}
[2024-09-15T23:49:09.479+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.479+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl-cocktails, task_id=obtencion-operator, run_id=scheduled__2024-08-29T00:00:00+00:00, execution_date=20240829T000000, start_date=20240915T234804, end_date=20240915T234909
[2024-09-15T23:49:09.486+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.486+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: etl-cocktails.obtencion-operator scheduled__2024-08-29T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-09-15T23:49:09.537+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:09.536+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:49:09.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 8.971 seconds
[2024-09-15T23:49:40.284+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:49:40.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:49:40.294+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:40.292+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:49:43.585+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:49:43.700+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:43.698+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:49:43.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 3.689 seconds
[2024-09-15T23:50:14.347+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:50:14.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:50:14.350+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:14.350+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:50:14.920+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:50:14.942+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:14.941+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:50:14.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.633 seconds
[2024-09-15T23:50:45.357+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:50:45.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:50:45.362+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:45.361+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:50:48.033+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:50:48.057+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:48.057+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:50:48.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 2.774 seconds
[2024-09-15T23:51:18.325+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:51:18.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:51:18.328+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:18.328+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:51:18.957+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:51:18.982+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:18.981+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:51:19.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.715 seconds
[2024-09-15T23:51:49.422+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:51:49.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:51:49.426+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:49.425+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:51:50.099+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:51:50.131+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:50.131+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:51:50.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.755 seconds
[2024-09-15T23:52:20.721+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:52:20.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:52:20.813+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:20.778+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:52:33.842+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:52:34.813+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:34.796+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:52:35.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 14.526 seconds
[2024-09-15T23:55:03.730+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:55:03.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:55:03.742+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:03.741+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:55:17.358+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:55:17.507+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:17.506+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:55:17.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 13.861 seconds
[2024-09-15T23:55:48.399+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:55:48.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:55:48.417+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:48.415+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:55:49.883+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:55:49.928+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:49.927+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:55:49.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 1.595 seconds
[2024-09-15T23:56:21.304+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:21.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:56:21.321+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:21.320+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:21.986+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:22.018+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:22.018+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:56:22.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.778 seconds
[2024-09-15T23:56:31.156+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:31.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:56:31.161+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:31.161+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:31.681+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:31.705+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:31.705+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:56:31.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.595 seconds
[2024-09-15T23:56:36.034+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:36.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:56:36.043+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:36.043+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:37.729+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:56:37.799+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:37.798+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:56:37.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 1.892 seconds
[2024-09-15T23:57:08.353+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:08.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:57:08.363+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:08.362+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:09.336+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:09.357+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:09.356+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:57:09.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 1.056 seconds
[2024-09-15T23:57:39.694+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:39.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:57:39.702+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:39.700+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:40.486+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:40.510+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:40.509+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:57:40.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 0.863 seconds
[2024-09-15T23:57:43.943+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:43.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_etl_cocktails.py for tasks to queue
[2024-09-15T23:57:43.949+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:43.949+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:46.850+0000] {processor.py:925} INFO - DAG(s) 'etl-cocktails' retrieved from /opt/airflow/dags/dag_etl_cocktails.py
[2024-09-15T23:57:46.876+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:46.875+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'etl-cocktails', 'Task Id': 'obtencion-operator', 'Run Id': 'scheduled__2024-08-27T00:00:00+00:00', 'Hostname': 'ef974a20a248', 'External Executor Id': '5300a1c2-4f13-4ab8-8b0c-5ace4f60eb42'}
[2024-09-15T23:57:46.994+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:46.994+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl-cocktails, task_id=obtencion-operator, run_id=scheduled__2024-08-27T00:00:00+00:00, execution_date=20240827T000000, start_date=20240915T235234, end_date=20240915T235746
[2024-09-15T23:57:47.018+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:47.018+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: etl-cocktails.obtencion-operator scheduled__2024-08-27T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-09-15T23:57:47.060+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:47.059+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:57:47.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_etl_cocktails.py took 3.166 seconds
